### ISSUE TITLE
应用在自定义dialog的时候,显示有些问题

### ISSUE THREAD

**Issue by yl82846094** [woxingxiao/FillBlankView#1]
我在自定义dialog的view布局里面用到了FillBlankView控件,当dialog显示的时候,FillBlankView是隐藏的,必须点击一次之后才会显示出来,但是在Activity的布局里面使用又没有这种情况,请问这如何解决呢?!

**Comment by woxingxiao** [comment]
解决方法（修正）：
```java
fillBlankView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
    @Override
    public void onGlobalLayout() {
    fillBlankView.getViewTreeObserver().removeGlobalOnLayoutListener(this);

    fillBlankView.post(new Runnable() {
         @Override
          public void run() {
              fillBlankView.invalidate();                   
          }
    });
  }
});
```
原因是在`Dialog`里时没有调用`onDraw()`，原因不明。所以外部手动触发`invalidate()`通知调用`onDraw()`就ok了。
@yl82846094 这个方法我已经亲自验证通过，enjoy

**Comment by yl82846094** [comment]
不好意思,现在才回复你.昨天有事儿请假了.

我按照你说的方法,但是还是不行, 点击之后就会显示正常显示出来, 我试着FillBlankView.performClick()模拟点击也是不行,你也可以试着写一个自定义布局的dialog试试看,会不会出现我这种情况,谢谢!
