### ISSUE TITLE
如何让输入框默认显示

### ISSUE THREAD

**Issue by ZhangKuixun** [woxingxiao/FillBlankView#3]
如何让输入框默认显示？

**Comment by woxingxiao** [comment]
我不明白

**Comment by ZhangKuixun** [comment]
我按照你说的方式创建出后不显示输入框，当输入一个字母后，才显示输入框

**Comment by woxingxiao** [comment]
没遇到过这种情况，亮码吧

**Comment by ZhangKuixun** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    style="@style/match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    tools:context="com.zhixun.extraterrestrial.ui.ARegister">

    <com.xw.repo.fillblankview.FillBlankView
        android:id="@+id/fill_blank_view2"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_marginLeft="@dimen/dp_20"
        android:layout_marginRight="@dimen/dp_20"
        android:padding="5dp"
        android:textColor="@color/c_ffffff"
        android:textSize="16sp"
        app:blankCornerRadius="0dp"
        app:blankSolidColor="@color/colorPrimary"
        app:blankSpace="@dimen/dp_16"
        app:blankStrokeColor="@color/c_323c45"
        app:blankStrokeWidth="1dp"
        app:isPasswordMode="false" />

</LinearLayout>

**Comment by woxingxiao** [comment]
==。。提问有关的代码最好都贴出来，我单从一个xml能看出什么来吗？不能

**Comment by ZhangKuixun** [comment]
```
@SuppressLint("Registered")
public class ARegister extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.a_register_);

    }
}

```
a_register_.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    style="@style/match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical">

    <com.xw.repo.fillblankview.FillBlankView
        android:id="@+id/fill_blank_view2"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_marginLeft="@dimen/dp_20"
        android:layout_marginRight="@dimen/dp_20"
        android:padding="5dp"
        android:textColor="@color/c_ffffff"
        android:textSize="16sp"
        app:blankCornerRadius="0dp"
        app:blankSolidColor="@color/colorPrimary"
        app:blankSpace="@dimen/dp_16"
        app:blankStrokeColor="@color/c_323c45"
        app:blankStrokeWidth="1dp"
        app:isPasswordMode="false" />

</LinearLayout>

```

manifest:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="....">

    <application
        android:name=".App"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme.NoActionBar">

        <activity
            android:name=".ui.ARegister"
            android:launchMode="singleTop" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
       
    </application>

</manifest>
```
styles:
 ```
   <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="android:colorPrimary">@color/colorPrimary</item>
        <item name="android:colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="android:colorAccent">@color/colorAccent</item>
        <item name="android:statusBarColor">@color/statusBarColor</item>
        <item name="android:windowBackground">@color/windowBackground</item>
    </style>

    <style name="AppTheme.NoActionBar" parent="AppTheme">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>
```

**Comment by woxingxiao** [comment]
== 不相关的就别贴了。。气鼓鼓。。看不出问题，不知道是不是你手机的问题。
几个尝试：
1. 去掉所有属性，运行看看；2. 换部手机运行看看；3. clone我的工程运行看看；4. 放弃这种交互（谁会用这种框来接收用户名输入？）

**Comment by ZhangKuixun** [comment]
好像是因为AppTheme.NoActionBar

**Comment by ZhangKuixun** [comment]
我把AppTheme撤了也不行了，不行了，你程序把我手机搞坏了

**Comment by ZhangKuixun** [comment]
有输入框：mRectFs = {RectF[6]@4712} 
 0 = {RectF@4786} "RectF(18.0, 18.0, -34.0, -18.0)"
 1 = {RectF@4814} "RectF(22.0, 18.0, -30.0, -18.0)"
 2 = {RectF@4815} "RectF(26.0, 18.0, -26.0, -18.0)"
 3 = {RectF@4816} "RectF(30.0, 18.0, -22.0, -18.0)"
 4 = {RectF@4817} "RectF(34.0, 18.0, -18.0, -18.0)"
 5 = {RectF@4818} "RectF(38.0, 18.0, -14.0, -18.0)"
无输入框： mRectFs = {RectF[6]@4712} 
0 = {RectF@5410} "RectF(18.0, 18.0, 182.0, 157.0)"
1 = {RectF@5282} "RectF(238.0, 18.0, 402.0, 157.0)"
2 = {RectF@5411} "RectF(458.0, 18.0, 622.0, 157.0)"
3 = {RectF@5412} "RectF(678.0, 18.0, 842.0, 157.0)"
4 = {RectF@5413} "RectF(898.0, 18.0, 1062.0, 157.0)"
5 = {RectF@5414} "RectF(1118.0, 18.0, 1282.0, 157.0)"

**Comment by woxingxiao** [comment]
说明最初输入框的宽度几乎没有，你的LinearLayout的用android:layout_width="match_parent"
        android:layout_height="match_parent"，别用你的style，试试看

**Comment by ZhangKuixun** [comment]
也不行，我直接把你的代码复制到我的工程里去，就好了，估计是library后使用的问题。
